### ISSUE TITLE
CORS error with docker image

### ISSUE THREAD

**Issue by Aman-Codes** [Shruti3004/FOSSology-REST-API#16]
### Description
CORS error when running the docker image of this repo for the FossologyUI project

#### How to reproduce
- Build the current docker image or Run `docker run -p 8081:80 amancodes/fossology-rest-api`
- Add the below credentials in `.env file`
```env
# following keys are required
#backend endpoint
REACT_APP_SERVER_URL=localhost:8081/repo/api/v2

#for enabling https for backend url
REACT_APP_HTTPS=false

#length of the random string for login
TOKEN_NAME_LENGTH=40

#by default the scope for user is to write
TOKEN_SCOPE=write

#authorization token expiry days
TOKEN_EXPIRY_DAYS = 2
```
- Run `yarn start`
- Try to login 

#### Screenshots

![image](https://user-images.githubusercontent.com/54680709/129519132-01edb24b-54f4-4399-9f6f-ec0584c8c445.png)

#### FOSSology logs

```
127.0.0.1 - - [16/Aug/2021:06:11:20 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) (internal dummy connection)"
[Mon Aug 16 06:11:35.651094 2021] [php7:notice] [pid 212] [client 172.17.0.1:51842] [2021-08-16 06:11:35] default.ERROR: RuntimeException: Callable Fossology\\UI\\Api\\Controllers\\AuthController does not exist in /usr/local/share/fossology/vendor/slim/slim/Slim/CallableResolver.php:99
Stack trace: #0 /usr/local/share/fossology/vendor/slim/slim/Slim/CallableResolver.php(58): Slim\\CallableResolver->resolveCallable('Fossology\\\\UI\\\\Ap...', 'optionsVerifica...')
#1 /usr/local/share/fossology/vendor/slim/slim/Slim/CallableResolverAwareTrait.php(41): Slim\\CallableResolver->resolve('Fossology\\\\UI\\\\Ap...')
#2 /usr/local/share/fossology/vendor/slim/slim/Slim/Route.php(276): Slim\\Routable->resolveCallable('Fossology\\\\UI\\\\Ap...')
#3 /usr/local/share/fossology/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#4 /usr/local/share/fossology/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#5 /usr/local/share/fossology/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#6 /usr/local/share/fossology/www/ui/api/Middlewares/FossologyInitMiddleware.php(52): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#7 [internal function]: Fossology\\UI\\Api\\Middlewares\\FossologyInitMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#8 /usr/local/share/fossology/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Fossology\\UI\\Api\\Middlewares\\FossologyInitMiddleware), Array)
#9 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#10 /usr/local/share/fossology/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#11 /usr/local/share/fossology/www/ui/api/Middlewares/RestAuthMiddleware.php(54): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#12 [internal function]: Fossology\\UI\\Api\\Middlewares\\RestAuthMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#13 /usr/local/share/fossology/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Fossology\\UI\\Api\\Middlewares\\RestAuthMiddleware), Array)
#14 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#15 /usr/local/share/fossology/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#16 /usr/local/share/fossology/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#17 /usr/local/share/fossology/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#18 /usr/local/share/fossology/vendor/slim/slim/Slim/App.php(297): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#19 /usr/local/share/fossology/www/ui/api/index.php(230): Slim\\App->run()
#20 {main} [] [], referer: http://localhost:3000/
172.17.0.1 - - [16/Aug/2021:06:11:35 +0000] "OPTIONS /repo/api/v2/tokens HTTP/1.1" 500 369 "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
```

##### General
Request URL: http://localhost:8081/repo/api/v2/tokens
Request Method: OPTIONS
Status Code: 500 Internal Server Error
Remote Address: [::1]:8081
Referrer Policy: strict-origin-when-cross-origin

##### Request Headers
OPTIONS /repo/api/v2/tokens HTTP/1.1
Host: localhost:8081
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

**Comment by kiranbaby14** [comment]
Hey can I work on this issue @Aman-Codes ?

**Comment by man0045** [comment]
is this issue still open if open then please it to me
